/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantinviteRouteImport } from './routes/tenantinvite'
import { Route as ResetpasswordRouteImport } from './routes/resetpassword'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as TenantUsersRouteImport } from './routes/tenant.users'
import { Route as TenantTeamsRouteImport } from './routes/tenant.teams'
import { Route as TenantTeamDeckRouteImport } from './routes/tenant.team-deck'
import { Route as TenantSettingsRouteImport } from './routes/tenant.settings'
import { Route as TenantSecurityRouteImport } from './routes/tenant.security'
import { Route as TenantRolesRouteImport } from './routes/tenant.roles'
import { Route as TenantPaymentsRouteImport } from './routes/tenant.payments'
import { Route as TenantOnboardingRouteImport } from './routes/tenant.onboarding'
import { Route as TenantMovedFilesRouteImport } from './routes/tenant.moved-files'
import { Route as TenantDashboardsRouteImport } from './routes/tenant.dashboards'
import { Route as TenantBillingRouteImport } from './routes/tenant.billing'
import { Route as TenantAuditRouteImport } from './routes/tenant.audit'
import { Route as TenantAssignmentRouteImport } from './routes/tenant.assignment'
import { Route as TenantAppointmentsRouteImport } from './routes/tenant.appointments'
import { Route as TenantSettingsIndexRouteImport } from './routes/tenant.settings.index'
import { Route as TenantPaymentsIndexRouteImport } from './routes/tenant.payments.index'
import { Route as TenantIntakeIndexRouteImport } from './routes/tenant.intake.index'
import { Route as TenantDebtorsIndexRouteImport } from './routes/tenant.debtors.index'
import { Route as TenantDashboardsIndexRouteImport } from './routes/tenant.dashboards.index'
import { Route as TenantCommsIndexRouteImport } from './routes/tenant.comms.index'
import { Route as TenantCaseFilesIndexRouteImport } from './routes/tenant.case-files.index'
import { Route as TenantSettingsStatusesRouteImport } from './routes/tenant.settings.statuses'
import { Route as TenantSettingsStatusAutomationRouteImport } from './routes/tenant.settings.status-automation'
import { Route as TenantSettingsDocumentAutomationRouteImport } from './routes/tenant.settings.document-automation'
import { Route as TenantPaymentsSettlementsRouteImport } from './routes/tenant.payments.settlements'
import { Route as TenantPaymentsPlansRouteImport } from './routes/tenant.payments.plans'
import { Route as TenantIntakeUploadRouteImport } from './routes/tenant.intake.upload'
import { Route as TenantIntakeMassUpdateRouteImport } from './routes/tenant.intake.mass-update'
import { Route as TenantIntakeImportRouteImport } from './routes/tenant.intake.import'
import { Route as TenantIntakeDedupeRouteImport } from './routes/tenant.intake.dedupe'
import { Route as TenantIntakeClientsRouteImport } from './routes/tenant.intake.clients'
import { Route as TenantIntakeAuditRouteImport } from './routes/tenant.intake.audit'
import { Route as TenantEngagementTemplateLibraryRouteImport } from './routes/tenant.engagement.template-library'
import { Route as TenantEngagementPhoneNumbersRouteImport } from './routes/tenant.engagement.phone-numbers'
import { Route as TenantDebtorsDebtorIdRouteImport } from './routes/tenant.debtors.$debtorId'
import { Route as TenantDashboardsSupervisorRouteImport } from './routes/tenant.dashboards.supervisor'
import { Route as TenantDashboardsScheduledRouteImport } from './routes/tenant.dashboards.scheduled'
import { Route as TenantDashboardsFinanceRouteImport } from './routes/tenant.dashboards.finance'
import { Route as TenantDashboardsExportsRouteImport } from './routes/tenant.dashboards.exports'
import { Route as TenantDashboardsExecutiveRouteImport } from './routes/tenant.dashboards.executive'
import { Route as TenantDashboardsCreditorsRouteImport } from './routes/tenant.dashboards.creditors'
import { Route as TenantDashboardsComplianceRouteImport } from './routes/tenant.dashboards.compliance'
import { Route as TenantDashboardsClientsRouteImport } from './routes/tenant.dashboards.clients'
import { Route as TenantDashboardsBuilderRouteImport } from './routes/tenant.dashboards.builder'
import { Route as TenantDashboardsAgentsRouteImport } from './routes/tenant.dashboards.agents'
import { Route as TenantCommsTemplatesRouteImport } from './routes/tenant.comms.templates'
import { Route as TenantCommsSmsRouteImport } from './routes/tenant.comms.sms'
import { Route as TenantCommsLettersRouteImport } from './routes/tenant.comms.letters'
import { Route as TenantCommsInboxRouteImport } from './routes/tenant.comms.inbox'
import { Route as TenantCommsHistoryRouteImport } from './routes/tenant.comms.history'
import { Route as TenantCommsEmailRouteImport } from './routes/tenant.comms.email'
import { Route as TenantCommsComplianceRouteImport } from './routes/tenant.comms.compliance'
import { Route as TenantCommsCampaignsRouteImport } from './routes/tenant.comms.campaigns'
import { Route as TenantCommsBulkRouteImport } from './routes/tenant.comms.bulk'
import { Route as TenantCommsAnalyticsRouteImport } from './routes/tenant.comms.analytics'
import { Route as TenantIntakeCrmIndexRouteImport } from './routes/tenant.intake.crm.index'
import { Route as TenantCommsLettersIndexRouteImport } from './routes/tenant.comms.letters.index'
import { Route as TenantIntakeCrmMappingsRouteImport } from './routes/tenant.intake.crm.mappings'
import { Route as TenantIntakeCrmConnectRouteImport } from './routes/tenant.intake.crm.connect'
import { Route as TenantIntakeCrmActivityRouteImport } from './routes/tenant.intake.crm.activity'
import { Route as TenantCommsLettersBulkRouteImport } from './routes/tenant.comms.letters.bulk'
import { Route as TenantCommsLettersBuilderRouteImport } from './routes/tenant.comms.letters.builder'
import { Route as TenantCommsLettersApprovalRouteImport } from './routes/tenant.comms.letters.approval'
import { Route as TenantDebtorsDebtorIdNotesNoteIdRouteImport } from './routes/tenant.debtors.$debtorId.notes.$noteId'
import { Route as TenantDebtorsDebtorIdCallsCallIdRouteImport } from './routes/tenant.debtors.$debtorId.calls.$callId'

const TenantinviteRoute = TenantinviteRouteImport.update({
  id: '/tenantinvite',
  path: '/tenantinvite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetpasswordRoute = ResetpasswordRouteImport.update({
  id: '/resetpassword',
  path: '/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantUsersRoute = TenantUsersRouteImport.update({
  id: '/tenant/users',
  path: '/tenant/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTeamsRoute = TenantTeamsRouteImport.update({
  id: '/tenant/teams',
  path: '/tenant/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTeamDeckRoute = TenantTeamDeckRouteImport.update({
  id: '/tenant/team-deck',
  path: '/tenant/team-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/tenant/settings',
  path: '/tenant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSecurityRoute = TenantSecurityRouteImport.update({
  id: '/tenant/security',
  path: '/tenant/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRolesRoute = TenantRolesRouteImport.update({
  id: '/tenant/roles',
  path: '/tenant/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPaymentsRoute = TenantPaymentsRouteImport.update({
  id: '/tenant/payments',
  path: '/tenant/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantOnboardingRoute = TenantOnboardingRouteImport.update({
  id: '/tenant/onboarding',
  path: '/tenant/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMovedFilesRoute = TenantMovedFilesRouteImport.update({
  id: '/tenant/moved-files',
  path: '/tenant/moved-files',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardsRoute = TenantDashboardsRouteImport.update({
  id: '/tenant/dashboards',
  path: '/tenant/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantBillingRoute = TenantBillingRouteImport.update({
  id: '/tenant/billing',
  path: '/tenant/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAuditRoute = TenantAuditRouteImport.update({
  id: '/tenant/audit',
  path: '/tenant/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAssignmentRoute = TenantAssignmentRouteImport.update({
  id: '/tenant/assignment',
  path: '/tenant/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAppointmentsRoute = TenantAppointmentsRouteImport.update({
  id: '/tenant/appointments',
  path: '/tenant/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettingsIndexRoute = TenantSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSettingsRoute,
} as any)
const TenantPaymentsIndexRoute = TenantPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantPaymentsRoute,
} as any)
const TenantIntakeIndexRoute = TenantIntakeIndexRouteImport.update({
  id: '/tenant/intake/',
  path: '/tenant/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDebtorsIndexRoute = TenantDebtorsIndexRouteImport.update({
  id: '/tenant/debtors/',
  path: '/tenant/debtors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardsIndexRoute = TenantDashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantDashboardsRoute,
} as any)
const TenantCommsIndexRoute = TenantCommsIndexRouteImport.update({
  id: '/tenant/comms/',
  path: '/tenant/comms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCaseFilesIndexRoute = TenantCaseFilesIndexRouteImport.update({
  id: '/tenant/case-files/',
  path: '/tenant/case-files/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettingsStatusesRoute = TenantSettingsStatusesRouteImport.update({
  id: '/statuses',
  path: '/statuses',
  getParentRoute: () => TenantSettingsRoute,
} as any)
const TenantSettingsStatusAutomationRoute =
  TenantSettingsStatusAutomationRouteImport.update({
    id: '/status-automation',
    path: '/status-automation',
    getParentRoute: () => TenantSettingsRoute,
  } as any)
const TenantSettingsDocumentAutomationRoute =
  TenantSettingsDocumentAutomationRouteImport.update({
    id: '/document-automation',
    path: '/document-automation',
    getParentRoute: () => TenantSettingsRoute,
  } as any)
const TenantPaymentsSettlementsRoute =
  TenantPaymentsSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => TenantPaymentsRoute,
  } as any)
const TenantPaymentsPlansRoute = TenantPaymentsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => TenantPaymentsRoute,
} as any)
const TenantIntakeUploadRoute = TenantIntakeUploadRouteImport.update({
  id: '/tenant/intake/upload',
  path: '/tenant/intake/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeMassUpdateRoute = TenantIntakeMassUpdateRouteImport.update({
  id: '/tenant/intake/mass-update',
  path: '/tenant/intake/mass-update',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeImportRoute = TenantIntakeImportRouteImport.update({
  id: '/tenant/intake/import',
  path: '/tenant/intake/import',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeDedupeRoute = TenantIntakeDedupeRouteImport.update({
  id: '/tenant/intake/dedupe',
  path: '/tenant/intake/dedupe',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeClientsRoute = TenantIntakeClientsRouteImport.update({
  id: '/tenant/intake/clients',
  path: '/tenant/intake/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeAuditRoute = TenantIntakeAuditRouteImport.update({
  id: '/tenant/intake/audit',
  path: '/tenant/intake/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantEngagementTemplateLibraryRoute =
  TenantEngagementTemplateLibraryRouteImport.update({
    id: '/tenant/engagement/template-library',
    path: '/tenant/engagement/template-library',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantEngagementPhoneNumbersRoute =
  TenantEngagementPhoneNumbersRouteImport.update({
    id: '/tenant/engagement/phone-numbers',
    path: '/tenant/engagement/phone-numbers',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantDebtorsDebtorIdRoute = TenantDebtorsDebtorIdRouteImport.update({
  id: '/tenant/debtors/$debtorId',
  path: '/tenant/debtors/$debtorId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardsSupervisorRoute =
  TenantDashboardsSupervisorRouteImport.update({
    id: '/supervisor',
    path: '/supervisor',
    getParentRoute: () => TenantDashboardsRoute,
  } as any)
const TenantDashboardsScheduledRoute =
  TenantDashboardsScheduledRouteImport.update({
    id: '/scheduled',
    path: '/scheduled',
    getParentRoute: () => TenantDashboardsRoute,
  } as any)
const TenantDashboardsFinanceRoute = TenantDashboardsFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => TenantDashboardsRoute,
} as any)
const TenantDashboardsExportsRoute = TenantDashboardsExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => TenantDashboardsRoute,
} as any)
const TenantDashboardsExecutiveRoute =
  TenantDashboardsExecutiveRouteImport.update({
    id: '/executive',
    path: '/executive',
    getParentRoute: () => TenantDashboardsRoute,
  } as any)
const TenantDashboardsCreditorsRoute =
  TenantDashboardsCreditorsRouteImport.update({
    id: '/creditors',
    path: '/creditors',
    getParentRoute: () => TenantDashboardsRoute,
  } as any)
const TenantDashboardsComplianceRoute =
  TenantDashboardsComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => TenantDashboardsRoute,
  } as any)
const TenantDashboardsClientsRoute = TenantDashboardsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => TenantDashboardsRoute,
} as any)
const TenantDashboardsBuilderRoute = TenantDashboardsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => TenantDashboardsRoute,
} as any)
const TenantDashboardsAgentsRoute = TenantDashboardsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => TenantDashboardsRoute,
} as any)
const TenantCommsTemplatesRoute = TenantCommsTemplatesRouteImport.update({
  id: '/tenant/comms/templates',
  path: '/tenant/comms/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsSmsRoute = TenantCommsSmsRouteImport.update({
  id: '/tenant/comms/sms',
  path: '/tenant/comms/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsLettersRoute = TenantCommsLettersRouteImport.update({
  id: '/tenant/comms/letters',
  path: '/tenant/comms/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsInboxRoute = TenantCommsInboxRouteImport.update({
  id: '/tenant/comms/inbox',
  path: '/tenant/comms/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsHistoryRoute = TenantCommsHistoryRouteImport.update({
  id: '/tenant/comms/history',
  path: '/tenant/comms/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsEmailRoute = TenantCommsEmailRouteImport.update({
  id: '/tenant/comms/email',
  path: '/tenant/comms/email',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsComplianceRoute = TenantCommsComplianceRouteImport.update({
  id: '/tenant/comms/compliance',
  path: '/tenant/comms/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsCampaignsRoute = TenantCommsCampaignsRouteImport.update({
  id: '/tenant/comms/campaigns',
  path: '/tenant/comms/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsBulkRoute = TenantCommsBulkRouteImport.update({
  id: '/tenant/comms/bulk',
  path: '/tenant/comms/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsAnalyticsRoute = TenantCommsAnalyticsRouteImport.update({
  id: '/tenant/comms/analytics',
  path: '/tenant/comms/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeCrmIndexRoute = TenantIntakeCrmIndexRouteImport.update({
  id: '/tenant/intake/crm/',
  path: '/tenant/intake/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsLettersIndexRoute = TenantCommsLettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantCommsLettersRoute,
} as any)
const TenantIntakeCrmMappingsRoute = TenantIntakeCrmMappingsRouteImport.update({
  id: '/tenant/intake/crm/mappings',
  path: '/tenant/intake/crm/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeCrmConnectRoute = TenantIntakeCrmConnectRouteImport.update({
  id: '/tenant/intake/crm/connect',
  path: '/tenant/intake/crm/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIntakeCrmActivityRoute = TenantIntakeCrmActivityRouteImport.update({
  id: '/tenant/intake/crm/activity',
  path: '/tenant/intake/crm/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantCommsLettersBulkRoute = TenantCommsLettersBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => TenantCommsLettersRoute,
} as any)
const TenantCommsLettersBuilderRoute =
  TenantCommsLettersBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => TenantCommsLettersRoute,
  } as any)
const TenantCommsLettersApprovalRoute =
  TenantCommsLettersApprovalRouteImport.update({
    id: '/approval',
    path: '/approval',
    getParentRoute: () => TenantCommsLettersRoute,
  } as any)
const TenantDebtorsDebtorIdNotesNoteIdRoute =
  TenantDebtorsDebtorIdNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => TenantDebtorsDebtorIdRoute,
  } as any)
const TenantDebtorsDebtorIdCallsCallIdRoute =
  TenantDebtorsDebtorIdCallsCallIdRouteImport.update({
    id: '/calls/$callId',
    path: '/calls/$callId',
    getParentRoute: () => TenantDebtorsDebtorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/tenantinvite': typeof TenantinviteRoute
  '/tenant/appointments': typeof TenantAppointmentsRoute
  '/tenant/assignment': typeof TenantAssignmentRoute
  '/tenant/audit': typeof TenantAuditRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/dashboards': typeof TenantDashboardsRouteWithChildren
  '/tenant/moved-files': typeof TenantMovedFilesRoute
  '/tenant/onboarding': typeof TenantOnboardingRoute
  '/tenant/payments': typeof TenantPaymentsRouteWithChildren
  '/tenant/roles': typeof TenantRolesRoute
  '/tenant/security': typeof TenantSecurityRoute
  '/tenant/settings': typeof TenantSettingsRouteWithChildren
  '/tenant/team-deck': typeof TenantTeamDeckRoute
  '/tenant/teams': typeof TenantTeamsRoute
  '/tenant/users': typeof TenantUsersRoute
  '/tenant/': typeof TenantIndexRoute
  '/tenant/comms/analytics': typeof TenantCommsAnalyticsRoute
  '/tenant/comms/bulk': typeof TenantCommsBulkRoute
  '/tenant/comms/campaigns': typeof TenantCommsCampaignsRoute
  '/tenant/comms/compliance': typeof TenantCommsComplianceRoute
  '/tenant/comms/email': typeof TenantCommsEmailRoute
  '/tenant/comms/history': typeof TenantCommsHistoryRoute
  '/tenant/comms/inbox': typeof TenantCommsInboxRoute
  '/tenant/comms/letters': typeof TenantCommsLettersRouteWithChildren
  '/tenant/comms/sms': typeof TenantCommsSmsRoute
  '/tenant/comms/templates': typeof TenantCommsTemplatesRoute
  '/tenant/dashboards/agents': typeof TenantDashboardsAgentsRoute
  '/tenant/dashboards/builder': typeof TenantDashboardsBuilderRoute
  '/tenant/dashboards/clients': typeof TenantDashboardsClientsRoute
  '/tenant/dashboards/compliance': typeof TenantDashboardsComplianceRoute
  '/tenant/dashboards/creditors': typeof TenantDashboardsCreditorsRoute
  '/tenant/dashboards/executive': typeof TenantDashboardsExecutiveRoute
  '/tenant/dashboards/exports': typeof TenantDashboardsExportsRoute
  '/tenant/dashboards/finance': typeof TenantDashboardsFinanceRoute
  '/tenant/dashboards/scheduled': typeof TenantDashboardsScheduledRoute
  '/tenant/dashboards/supervisor': typeof TenantDashboardsSupervisorRoute
  '/tenant/debtors/$debtorId': typeof TenantDebtorsDebtorIdRouteWithChildren
  '/tenant/engagement/phone-numbers': typeof TenantEngagementPhoneNumbersRoute
  '/tenant/engagement/template-library': typeof TenantEngagementTemplateLibraryRoute
  '/tenant/intake/audit': typeof TenantIntakeAuditRoute
  '/tenant/intake/clients': typeof TenantIntakeClientsRoute
  '/tenant/intake/dedupe': typeof TenantIntakeDedupeRoute
  '/tenant/intake/import': typeof TenantIntakeImportRoute
  '/tenant/intake/mass-update': typeof TenantIntakeMassUpdateRoute
  '/tenant/intake/upload': typeof TenantIntakeUploadRoute
  '/tenant/payments/plans': typeof TenantPaymentsPlansRoute
  '/tenant/payments/settlements': typeof TenantPaymentsSettlementsRoute
  '/tenant/settings/document-automation': typeof TenantSettingsDocumentAutomationRoute
  '/tenant/settings/status-automation': typeof TenantSettingsStatusAutomationRoute
  '/tenant/settings/statuses': typeof TenantSettingsStatusesRoute
  '/tenant/case-files/': typeof TenantCaseFilesIndexRoute
  '/tenant/comms/': typeof TenantCommsIndexRoute
  '/tenant/dashboards/': typeof TenantDashboardsIndexRoute
  '/tenant/debtors/': typeof TenantDebtorsIndexRoute
  '/tenant/intake/': typeof TenantIntakeIndexRoute
  '/tenant/payments/': typeof TenantPaymentsIndexRoute
  '/tenant/settings/': typeof TenantSettingsIndexRoute
  '/tenant/comms/letters/approval': typeof TenantCommsLettersApprovalRoute
  '/tenant/comms/letters/builder': typeof TenantCommsLettersBuilderRoute
  '/tenant/comms/letters/bulk': typeof TenantCommsLettersBulkRoute
  '/tenant/intake/crm/activity': typeof TenantIntakeCrmActivityRoute
  '/tenant/intake/crm/connect': typeof TenantIntakeCrmConnectRoute
  '/tenant/intake/crm/mappings': typeof TenantIntakeCrmMappingsRoute
  '/tenant/comms/letters/': typeof TenantCommsLettersIndexRoute
  '/tenant/intake/crm/': typeof TenantIntakeCrmIndexRoute
  '/tenant/debtors/$debtorId/calls/$callId': typeof TenantDebtorsDebtorIdCallsCallIdRoute
  '/tenant/debtors/$debtorId/notes/$noteId': typeof TenantDebtorsDebtorIdNotesNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/tenantinvite': typeof TenantinviteRoute
  '/tenant/appointments': typeof TenantAppointmentsRoute
  '/tenant/assignment': typeof TenantAssignmentRoute
  '/tenant/audit': typeof TenantAuditRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/moved-files': typeof TenantMovedFilesRoute
  '/tenant/onboarding': typeof TenantOnboardingRoute
  '/tenant/roles': typeof TenantRolesRoute
  '/tenant/security': typeof TenantSecurityRoute
  '/tenant/team-deck': typeof TenantTeamDeckRoute
  '/tenant/teams': typeof TenantTeamsRoute
  '/tenant/users': typeof TenantUsersRoute
  '/tenant': typeof TenantIndexRoute
  '/tenant/comms/analytics': typeof TenantCommsAnalyticsRoute
  '/tenant/comms/bulk': typeof TenantCommsBulkRoute
  '/tenant/comms/campaigns': typeof TenantCommsCampaignsRoute
  '/tenant/comms/compliance': typeof TenantCommsComplianceRoute
  '/tenant/comms/email': typeof TenantCommsEmailRoute
  '/tenant/comms/history': typeof TenantCommsHistoryRoute
  '/tenant/comms/inbox': typeof TenantCommsInboxRoute
  '/tenant/comms/sms': typeof TenantCommsSmsRoute
  '/tenant/comms/templates': typeof TenantCommsTemplatesRoute
  '/tenant/dashboards/agents': typeof TenantDashboardsAgentsRoute
  '/tenant/dashboards/builder': typeof TenantDashboardsBuilderRoute
  '/tenant/dashboards/clients': typeof TenantDashboardsClientsRoute
  '/tenant/dashboards/compliance': typeof TenantDashboardsComplianceRoute
  '/tenant/dashboards/creditors': typeof TenantDashboardsCreditorsRoute
  '/tenant/dashboards/executive': typeof TenantDashboardsExecutiveRoute
  '/tenant/dashboards/exports': typeof TenantDashboardsExportsRoute
  '/tenant/dashboards/finance': typeof TenantDashboardsFinanceRoute
  '/tenant/dashboards/scheduled': typeof TenantDashboardsScheduledRoute
  '/tenant/dashboards/supervisor': typeof TenantDashboardsSupervisorRoute
  '/tenant/debtors/$debtorId': typeof TenantDebtorsDebtorIdRouteWithChildren
  '/tenant/engagement/phone-numbers': typeof TenantEngagementPhoneNumbersRoute
  '/tenant/engagement/template-library': typeof TenantEngagementTemplateLibraryRoute
  '/tenant/intake/audit': typeof TenantIntakeAuditRoute
  '/tenant/intake/clients': typeof TenantIntakeClientsRoute
  '/tenant/intake/dedupe': typeof TenantIntakeDedupeRoute
  '/tenant/intake/import': typeof TenantIntakeImportRoute
  '/tenant/intake/mass-update': typeof TenantIntakeMassUpdateRoute
  '/tenant/intake/upload': typeof TenantIntakeUploadRoute
  '/tenant/payments/plans': typeof TenantPaymentsPlansRoute
  '/tenant/payments/settlements': typeof TenantPaymentsSettlementsRoute
  '/tenant/settings/document-automation': typeof TenantSettingsDocumentAutomationRoute
  '/tenant/settings/status-automation': typeof TenantSettingsStatusAutomationRoute
  '/tenant/settings/statuses': typeof TenantSettingsStatusesRoute
  '/tenant/case-files': typeof TenantCaseFilesIndexRoute
  '/tenant/comms': typeof TenantCommsIndexRoute
  '/tenant/dashboards': typeof TenantDashboardsIndexRoute
  '/tenant/debtors': typeof TenantDebtorsIndexRoute
  '/tenant/intake': typeof TenantIntakeIndexRoute
  '/tenant/payments': typeof TenantPaymentsIndexRoute
  '/tenant/settings': typeof TenantSettingsIndexRoute
  '/tenant/comms/letters/approval': typeof TenantCommsLettersApprovalRoute
  '/tenant/comms/letters/builder': typeof TenantCommsLettersBuilderRoute
  '/tenant/comms/letters/bulk': typeof TenantCommsLettersBulkRoute
  '/tenant/intake/crm/activity': typeof TenantIntakeCrmActivityRoute
  '/tenant/intake/crm/connect': typeof TenantIntakeCrmConnectRoute
  '/tenant/intake/crm/mappings': typeof TenantIntakeCrmMappingsRoute
  '/tenant/comms/letters': typeof TenantCommsLettersIndexRoute
  '/tenant/intake/crm': typeof TenantIntakeCrmIndexRoute
  '/tenant/debtors/$debtorId/calls/$callId': typeof TenantDebtorsDebtorIdCallsCallIdRoute
  '/tenant/debtors/$debtorId/notes/$noteId': typeof TenantDebtorsDebtorIdNotesNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/tenantinvite': typeof TenantinviteRoute
  '/tenant/appointments': typeof TenantAppointmentsRoute
  '/tenant/assignment': typeof TenantAssignmentRoute
  '/tenant/audit': typeof TenantAuditRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/dashboards': typeof TenantDashboardsRouteWithChildren
  '/tenant/moved-files': typeof TenantMovedFilesRoute
  '/tenant/onboarding': typeof TenantOnboardingRoute
  '/tenant/payments': typeof TenantPaymentsRouteWithChildren
  '/tenant/roles': typeof TenantRolesRoute
  '/tenant/security': typeof TenantSecurityRoute
  '/tenant/settings': typeof TenantSettingsRouteWithChildren
  '/tenant/team-deck': typeof TenantTeamDeckRoute
  '/tenant/teams': typeof TenantTeamsRoute
  '/tenant/users': typeof TenantUsersRoute
  '/tenant/': typeof TenantIndexRoute
  '/tenant/comms/analytics': typeof TenantCommsAnalyticsRoute
  '/tenant/comms/bulk': typeof TenantCommsBulkRoute
  '/tenant/comms/campaigns': typeof TenantCommsCampaignsRoute
  '/tenant/comms/compliance': typeof TenantCommsComplianceRoute
  '/tenant/comms/email': typeof TenantCommsEmailRoute
  '/tenant/comms/history': typeof TenantCommsHistoryRoute
  '/tenant/comms/inbox': typeof TenantCommsInboxRoute
  '/tenant/comms/letters': typeof TenantCommsLettersRouteWithChildren
  '/tenant/comms/sms': typeof TenantCommsSmsRoute
  '/tenant/comms/templates': typeof TenantCommsTemplatesRoute
  '/tenant/dashboards/agents': typeof TenantDashboardsAgentsRoute
  '/tenant/dashboards/builder': typeof TenantDashboardsBuilderRoute
  '/tenant/dashboards/clients': typeof TenantDashboardsClientsRoute
  '/tenant/dashboards/compliance': typeof TenantDashboardsComplianceRoute
  '/tenant/dashboards/creditors': typeof TenantDashboardsCreditorsRoute
  '/tenant/dashboards/executive': typeof TenantDashboardsExecutiveRoute
  '/tenant/dashboards/exports': typeof TenantDashboardsExportsRoute
  '/tenant/dashboards/finance': typeof TenantDashboardsFinanceRoute
  '/tenant/dashboards/scheduled': typeof TenantDashboardsScheduledRoute
  '/tenant/dashboards/supervisor': typeof TenantDashboardsSupervisorRoute
  '/tenant/debtors/$debtorId': typeof TenantDebtorsDebtorIdRouteWithChildren
  '/tenant/engagement/phone-numbers': typeof TenantEngagementPhoneNumbersRoute
  '/tenant/engagement/template-library': typeof TenantEngagementTemplateLibraryRoute
  '/tenant/intake/audit': typeof TenantIntakeAuditRoute
  '/tenant/intake/clients': typeof TenantIntakeClientsRoute
  '/tenant/intake/dedupe': typeof TenantIntakeDedupeRoute
  '/tenant/intake/import': typeof TenantIntakeImportRoute
  '/tenant/intake/mass-update': typeof TenantIntakeMassUpdateRoute
  '/tenant/intake/upload': typeof TenantIntakeUploadRoute
  '/tenant/payments/plans': typeof TenantPaymentsPlansRoute
  '/tenant/payments/settlements': typeof TenantPaymentsSettlementsRoute
  '/tenant/settings/document-automation': typeof TenantSettingsDocumentAutomationRoute
  '/tenant/settings/status-automation': typeof TenantSettingsStatusAutomationRoute
  '/tenant/settings/statuses': typeof TenantSettingsStatusesRoute
  '/tenant/case-files/': typeof TenantCaseFilesIndexRoute
  '/tenant/comms/': typeof TenantCommsIndexRoute
  '/tenant/dashboards/': typeof TenantDashboardsIndexRoute
  '/tenant/debtors/': typeof TenantDebtorsIndexRoute
  '/tenant/intake/': typeof TenantIntakeIndexRoute
  '/tenant/payments/': typeof TenantPaymentsIndexRoute
  '/tenant/settings/': typeof TenantSettingsIndexRoute
  '/tenant/comms/letters/approval': typeof TenantCommsLettersApprovalRoute
  '/tenant/comms/letters/builder': typeof TenantCommsLettersBuilderRoute
  '/tenant/comms/letters/bulk': typeof TenantCommsLettersBulkRoute
  '/tenant/intake/crm/activity': typeof TenantIntakeCrmActivityRoute
  '/tenant/intake/crm/connect': typeof TenantIntakeCrmConnectRoute
  '/tenant/intake/crm/mappings': typeof TenantIntakeCrmMappingsRoute
  '/tenant/comms/letters/': typeof TenantCommsLettersIndexRoute
  '/tenant/intake/crm/': typeof TenantIntakeCrmIndexRoute
  '/tenant/debtors/$debtorId/calls/$callId': typeof TenantDebtorsDebtorIdCallsCallIdRoute
  '/tenant/debtors/$debtorId/notes/$noteId': typeof TenantDebtorsDebtorIdNotesNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/resetpassword'
    | '/tenantinvite'
    | '/tenant/appointments'
    | '/tenant/assignment'
    | '/tenant/audit'
    | '/tenant/billing'
    | '/tenant/dashboards'
    | '/tenant/moved-files'
    | '/tenant/onboarding'
    | '/tenant/payments'
    | '/tenant/roles'
    | '/tenant/security'
    | '/tenant/settings'
    | '/tenant/team-deck'
    | '/tenant/teams'
    | '/tenant/users'
    | '/tenant/'
    | '/tenant/comms/analytics'
    | '/tenant/comms/bulk'
    | '/tenant/comms/campaigns'
    | '/tenant/comms/compliance'
    | '/tenant/comms/email'
    | '/tenant/comms/history'
    | '/tenant/comms/inbox'
    | '/tenant/comms/letters'
    | '/tenant/comms/sms'
    | '/tenant/comms/templates'
    | '/tenant/dashboards/agents'
    | '/tenant/dashboards/builder'
    | '/tenant/dashboards/clients'
    | '/tenant/dashboards/compliance'
    | '/tenant/dashboards/creditors'
    | '/tenant/dashboards/executive'
    | '/tenant/dashboards/exports'
    | '/tenant/dashboards/finance'
    | '/tenant/dashboards/scheduled'
    | '/tenant/dashboards/supervisor'
    | '/tenant/debtors/$debtorId'
    | '/tenant/engagement/phone-numbers'
    | '/tenant/engagement/template-library'
    | '/tenant/intake/audit'
    | '/tenant/intake/clients'
    | '/tenant/intake/dedupe'
    | '/tenant/intake/import'
    | '/tenant/intake/mass-update'
    | '/tenant/intake/upload'
    | '/tenant/payments/plans'
    | '/tenant/payments/settlements'
    | '/tenant/settings/document-automation'
    | '/tenant/settings/status-automation'
    | '/tenant/settings/statuses'
    | '/tenant/case-files/'
    | '/tenant/comms/'
    | '/tenant/dashboards/'
    | '/tenant/debtors/'
    | '/tenant/intake/'
    | '/tenant/payments/'
    | '/tenant/settings/'
    | '/tenant/comms/letters/approval'
    | '/tenant/comms/letters/builder'
    | '/tenant/comms/letters/bulk'
    | '/tenant/intake/crm/activity'
    | '/tenant/intake/crm/connect'
    | '/tenant/intake/crm/mappings'
    | '/tenant/comms/letters/'
    | '/tenant/intake/crm/'
    | '/tenant/debtors/$debtorId/calls/$callId'
    | '/tenant/debtors/$debtorId/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/resetpassword'
    | '/tenantinvite'
    | '/tenant/appointments'
    | '/tenant/assignment'
    | '/tenant/audit'
    | '/tenant/billing'
    | '/tenant/moved-files'
    | '/tenant/onboarding'
    | '/tenant/roles'
    | '/tenant/security'
    | '/tenant/team-deck'
    | '/tenant/teams'
    | '/tenant/users'
    | '/tenant'
    | '/tenant/comms/analytics'
    | '/tenant/comms/bulk'
    | '/tenant/comms/campaigns'
    | '/tenant/comms/compliance'
    | '/tenant/comms/email'
    | '/tenant/comms/history'
    | '/tenant/comms/inbox'
    | '/tenant/comms/sms'
    | '/tenant/comms/templates'
    | '/tenant/dashboards/agents'
    | '/tenant/dashboards/builder'
    | '/tenant/dashboards/clients'
    | '/tenant/dashboards/compliance'
    | '/tenant/dashboards/creditors'
    | '/tenant/dashboards/executive'
    | '/tenant/dashboards/exports'
    | '/tenant/dashboards/finance'
    | '/tenant/dashboards/scheduled'
    | '/tenant/dashboards/supervisor'
    | '/tenant/debtors/$debtorId'
    | '/tenant/engagement/phone-numbers'
    | '/tenant/engagement/template-library'
    | '/tenant/intake/audit'
    | '/tenant/intake/clients'
    | '/tenant/intake/dedupe'
    | '/tenant/intake/import'
    | '/tenant/intake/mass-update'
    | '/tenant/intake/upload'
    | '/tenant/payments/plans'
    | '/tenant/payments/settlements'
    | '/tenant/settings/document-automation'
    | '/tenant/settings/status-automation'
    | '/tenant/settings/statuses'
    | '/tenant/case-files'
    | '/tenant/comms'
    | '/tenant/dashboards'
    | '/tenant/debtors'
    | '/tenant/intake'
    | '/tenant/payments'
    | '/tenant/settings'
    | '/tenant/comms/letters/approval'
    | '/tenant/comms/letters/builder'
    | '/tenant/comms/letters/bulk'
    | '/tenant/intake/crm/activity'
    | '/tenant/intake/crm/connect'
    | '/tenant/intake/crm/mappings'
    | '/tenant/comms/letters'
    | '/tenant/intake/crm'
    | '/tenant/debtors/$debtorId/calls/$callId'
    | '/tenant/debtors/$debtorId/notes/$noteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reset-password'
    | '/resetpassword'
    | '/tenantinvite'
    | '/tenant/appointments'
    | '/tenant/assignment'
    | '/tenant/audit'
    | '/tenant/billing'
    | '/tenant/dashboards'
    | '/tenant/moved-files'
    | '/tenant/onboarding'
    | '/tenant/payments'
    | '/tenant/roles'
    | '/tenant/security'
    | '/tenant/settings'
    | '/tenant/team-deck'
    | '/tenant/teams'
    | '/tenant/users'
    | '/tenant/'
    | '/tenant/comms/analytics'
    | '/tenant/comms/bulk'
    | '/tenant/comms/campaigns'
    | '/tenant/comms/compliance'
    | '/tenant/comms/email'
    | '/tenant/comms/history'
    | '/tenant/comms/inbox'
    | '/tenant/comms/letters'
    | '/tenant/comms/sms'
    | '/tenant/comms/templates'
    | '/tenant/dashboards/agents'
    | '/tenant/dashboards/builder'
    | '/tenant/dashboards/clients'
    | '/tenant/dashboards/compliance'
    | '/tenant/dashboards/creditors'
    | '/tenant/dashboards/executive'
    | '/tenant/dashboards/exports'
    | '/tenant/dashboards/finance'
    | '/tenant/dashboards/scheduled'
    | '/tenant/dashboards/supervisor'
    | '/tenant/debtors/$debtorId'
    | '/tenant/engagement/phone-numbers'
    | '/tenant/engagement/template-library'
    | '/tenant/intake/audit'
    | '/tenant/intake/clients'
    | '/tenant/intake/dedupe'
    | '/tenant/intake/import'
    | '/tenant/intake/mass-update'
    | '/tenant/intake/upload'
    | '/tenant/payments/plans'
    | '/tenant/payments/settlements'
    | '/tenant/settings/document-automation'
    | '/tenant/settings/status-automation'
    | '/tenant/settings/statuses'
    | '/tenant/case-files/'
    | '/tenant/comms/'
    | '/tenant/dashboards/'
    | '/tenant/debtors/'
    | '/tenant/intake/'
    | '/tenant/payments/'
    | '/tenant/settings/'
    | '/tenant/comms/letters/approval'
    | '/tenant/comms/letters/builder'
    | '/tenant/comms/letters/bulk'
    | '/tenant/intake/crm/activity'
    | '/tenant/intake/crm/connect'
    | '/tenant/intake/crm/mappings'
    | '/tenant/comms/letters/'
    | '/tenant/intake/crm/'
    | '/tenant/debtors/$debtorId/calls/$callId'
    | '/tenant/debtors/$debtorId/notes/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetpasswordRoute: typeof ResetpasswordRoute
  TenantinviteRoute: typeof TenantinviteRoute
  TenantAppointmentsRoute: typeof TenantAppointmentsRoute
  TenantAssignmentRoute: typeof TenantAssignmentRoute
  TenantAuditRoute: typeof TenantAuditRoute
  TenantBillingRoute: typeof TenantBillingRoute
  TenantDashboardsRoute: typeof TenantDashboardsRouteWithChildren
  TenantMovedFilesRoute: typeof TenantMovedFilesRoute
  TenantOnboardingRoute: typeof TenantOnboardingRoute
  TenantPaymentsRoute: typeof TenantPaymentsRouteWithChildren
  TenantRolesRoute: typeof TenantRolesRoute
  TenantSecurityRoute: typeof TenantSecurityRoute
  TenantSettingsRoute: typeof TenantSettingsRouteWithChildren
  TenantTeamDeckRoute: typeof TenantTeamDeckRoute
  TenantTeamsRoute: typeof TenantTeamsRoute
  TenantUsersRoute: typeof TenantUsersRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantCommsAnalyticsRoute: typeof TenantCommsAnalyticsRoute
  TenantCommsBulkRoute: typeof TenantCommsBulkRoute
  TenantCommsCampaignsRoute: typeof TenantCommsCampaignsRoute
  TenantCommsComplianceRoute: typeof TenantCommsComplianceRoute
  TenantCommsEmailRoute: typeof TenantCommsEmailRoute
  TenantCommsHistoryRoute: typeof TenantCommsHistoryRoute
  TenantCommsInboxRoute: typeof TenantCommsInboxRoute
  TenantCommsLettersRoute: typeof TenantCommsLettersRouteWithChildren
  TenantCommsSmsRoute: typeof TenantCommsSmsRoute
  TenantCommsTemplatesRoute: typeof TenantCommsTemplatesRoute
  TenantDebtorsDebtorIdRoute: typeof TenantDebtorsDebtorIdRouteWithChildren
  TenantEngagementPhoneNumbersRoute: typeof TenantEngagementPhoneNumbersRoute
  TenantEngagementTemplateLibraryRoute: typeof TenantEngagementTemplateLibraryRoute
  TenantIntakeAuditRoute: typeof TenantIntakeAuditRoute
  TenantIntakeClientsRoute: typeof TenantIntakeClientsRoute
  TenantIntakeDedupeRoute: typeof TenantIntakeDedupeRoute
  TenantIntakeImportRoute: typeof TenantIntakeImportRoute
  TenantIntakeMassUpdateRoute: typeof TenantIntakeMassUpdateRoute
  TenantIntakeUploadRoute: typeof TenantIntakeUploadRoute
  TenantCaseFilesIndexRoute: typeof TenantCaseFilesIndexRoute
  TenantCommsIndexRoute: typeof TenantCommsIndexRoute
  TenantDebtorsIndexRoute: typeof TenantDebtorsIndexRoute
  TenantIntakeIndexRoute: typeof TenantIntakeIndexRoute
  TenantIntakeCrmActivityRoute: typeof TenantIntakeCrmActivityRoute
  TenantIntakeCrmConnectRoute: typeof TenantIntakeCrmConnectRoute
  TenantIntakeCrmMappingsRoute: typeof TenantIntakeCrmMappingsRoute
  TenantIntakeCrmIndexRoute: typeof TenantIntakeCrmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenantinvite': {
      id: '/tenantinvite'
      path: '/tenantinvite'
      fullPath: '/tenantinvite'
      preLoaderRoute: typeof TenantinviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetpassword': {
      id: '/resetpassword'
      path: '/resetpassword'
      fullPath: '/resetpassword'
      preLoaderRoute: typeof ResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/users': {
      id: '/tenant/users'
      path: '/tenant/users'
      fullPath: '/tenant/users'
      preLoaderRoute: typeof TenantUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/teams': {
      id: '/tenant/teams'
      path: '/tenant/teams'
      fullPath: '/tenant/teams'
      preLoaderRoute: typeof TenantTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/team-deck': {
      id: '/tenant/team-deck'
      path: '/tenant/team-deck'
      fullPath: '/tenant/team-deck'
      preLoaderRoute: typeof TenantTeamDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settings': {
      id: '/tenant/settings'
      path: '/tenant/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/security': {
      id: '/tenant/security'
      path: '/tenant/security'
      fullPath: '/tenant/security'
      preLoaderRoute: typeof TenantSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/roles': {
      id: '/tenant/roles'
      path: '/tenant/roles'
      fullPath: '/tenant/roles'
      preLoaderRoute: typeof TenantRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/onboarding': {
      id: '/tenant/onboarding'
      path: '/tenant/onboarding'
      fullPath: '/tenant/onboarding'
      preLoaderRoute: typeof TenantOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/moved-files': {
      id: '/tenant/moved-files'
      path: '/tenant/moved-files'
      fullPath: '/tenant/moved-files'
      preLoaderRoute: typeof TenantMovedFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/dashboards': {
      id: '/tenant/dashboards'
      path: '/tenant/dashboards'
      fullPath: '/tenant/dashboards'
      preLoaderRoute: typeof TenantDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/billing': {
      id: '/tenant/billing'
      path: '/tenant/billing'
      fullPath: '/tenant/billing'
      preLoaderRoute: typeof TenantBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/audit': {
      id: '/tenant/audit'
      path: '/tenant/audit'
      fullPath: '/tenant/audit'
      preLoaderRoute: typeof TenantAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/assignment': {
      id: '/tenant/assignment'
      path: '/tenant/assignment'
      fullPath: '/tenant/assignment'
      preLoaderRoute: typeof TenantAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/appointments': {
      id: '/tenant/appointments'
      path: '/tenant/appointments'
      fullPath: '/tenant/appointments'
      preLoaderRoute: typeof TenantAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settings/': {
      id: '/tenant/settings/'
      path: '/'
      fullPath: '/tenant/settings/'
      preLoaderRoute: typeof TenantSettingsIndexRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/tenant/payments/': {
      id: '/tenant/payments/'
      path: '/'
      fullPath: '/tenant/payments/'
      preLoaderRoute: typeof TenantPaymentsIndexRouteImport
      parentRoute: typeof TenantPaymentsRoute
    }
    '/tenant/intake/': {
      id: '/tenant/intake/'
      path: '/tenant/intake'
      fullPath: '/tenant/intake/'
      preLoaderRoute: typeof TenantIntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/debtors/': {
      id: '/tenant/debtors/'
      path: '/tenant/debtors'
      fullPath: '/tenant/debtors/'
      preLoaderRoute: typeof TenantDebtorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/dashboards/': {
      id: '/tenant/dashboards/'
      path: '/'
      fullPath: '/tenant/dashboards/'
      preLoaderRoute: typeof TenantDashboardsIndexRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/comms/': {
      id: '/tenant/comms/'
      path: '/tenant/comms'
      fullPath: '/tenant/comms/'
      preLoaderRoute: typeof TenantCommsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/case-files/': {
      id: '/tenant/case-files/'
      path: '/tenant/case-files'
      fullPath: '/tenant/case-files/'
      preLoaderRoute: typeof TenantCaseFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settings/statuses': {
      id: '/tenant/settings/statuses'
      path: '/statuses'
      fullPath: '/tenant/settings/statuses'
      preLoaderRoute: typeof TenantSettingsStatusesRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/tenant/settings/status-automation': {
      id: '/tenant/settings/status-automation'
      path: '/status-automation'
      fullPath: '/tenant/settings/status-automation'
      preLoaderRoute: typeof TenantSettingsStatusAutomationRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/tenant/settings/document-automation': {
      id: '/tenant/settings/document-automation'
      path: '/document-automation'
      fullPath: '/tenant/settings/document-automation'
      preLoaderRoute: typeof TenantSettingsDocumentAutomationRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/tenant/payments/settlements': {
      id: '/tenant/payments/settlements'
      path: '/settlements'
      fullPath: '/tenant/payments/settlements'
      preLoaderRoute: typeof TenantPaymentsSettlementsRouteImport
      parentRoute: typeof TenantPaymentsRoute
    }
    '/tenant/payments/plans': {
      id: '/tenant/payments/plans'
      path: '/plans'
      fullPath: '/tenant/payments/plans'
      preLoaderRoute: typeof TenantPaymentsPlansRouteImport
      parentRoute: typeof TenantPaymentsRoute
    }
    '/tenant/intake/upload': {
      id: '/tenant/intake/upload'
      path: '/tenant/intake/upload'
      fullPath: '/tenant/intake/upload'
      preLoaderRoute: typeof TenantIntakeUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/mass-update': {
      id: '/tenant/intake/mass-update'
      path: '/tenant/intake/mass-update'
      fullPath: '/tenant/intake/mass-update'
      preLoaderRoute: typeof TenantIntakeMassUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/import': {
      id: '/tenant/intake/import'
      path: '/tenant/intake/import'
      fullPath: '/tenant/intake/import'
      preLoaderRoute: typeof TenantIntakeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/dedupe': {
      id: '/tenant/intake/dedupe'
      path: '/tenant/intake/dedupe'
      fullPath: '/tenant/intake/dedupe'
      preLoaderRoute: typeof TenantIntakeDedupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/clients': {
      id: '/tenant/intake/clients'
      path: '/tenant/intake/clients'
      fullPath: '/tenant/intake/clients'
      preLoaderRoute: typeof TenantIntakeClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/audit': {
      id: '/tenant/intake/audit'
      path: '/tenant/intake/audit'
      fullPath: '/tenant/intake/audit'
      preLoaderRoute: typeof TenantIntakeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/engagement/template-library': {
      id: '/tenant/engagement/template-library'
      path: '/tenant/engagement/template-library'
      fullPath: '/tenant/engagement/template-library'
      preLoaderRoute: typeof TenantEngagementTemplateLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/engagement/phone-numbers': {
      id: '/tenant/engagement/phone-numbers'
      path: '/tenant/engagement/phone-numbers'
      fullPath: '/tenant/engagement/phone-numbers'
      preLoaderRoute: typeof TenantEngagementPhoneNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/debtors/$debtorId': {
      id: '/tenant/debtors/$debtorId'
      path: '/tenant/debtors/$debtorId'
      fullPath: '/tenant/debtors/$debtorId'
      preLoaderRoute: typeof TenantDebtorsDebtorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/dashboards/supervisor': {
      id: '/tenant/dashboards/supervisor'
      path: '/supervisor'
      fullPath: '/tenant/dashboards/supervisor'
      preLoaderRoute: typeof TenantDashboardsSupervisorRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/scheduled': {
      id: '/tenant/dashboards/scheduled'
      path: '/scheduled'
      fullPath: '/tenant/dashboards/scheduled'
      preLoaderRoute: typeof TenantDashboardsScheduledRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/finance': {
      id: '/tenant/dashboards/finance'
      path: '/finance'
      fullPath: '/tenant/dashboards/finance'
      preLoaderRoute: typeof TenantDashboardsFinanceRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/exports': {
      id: '/tenant/dashboards/exports'
      path: '/exports'
      fullPath: '/tenant/dashboards/exports'
      preLoaderRoute: typeof TenantDashboardsExportsRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/executive': {
      id: '/tenant/dashboards/executive'
      path: '/executive'
      fullPath: '/tenant/dashboards/executive'
      preLoaderRoute: typeof TenantDashboardsExecutiveRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/creditors': {
      id: '/tenant/dashboards/creditors'
      path: '/creditors'
      fullPath: '/tenant/dashboards/creditors'
      preLoaderRoute: typeof TenantDashboardsCreditorsRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/compliance': {
      id: '/tenant/dashboards/compliance'
      path: '/compliance'
      fullPath: '/tenant/dashboards/compliance'
      preLoaderRoute: typeof TenantDashboardsComplianceRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/clients': {
      id: '/tenant/dashboards/clients'
      path: '/clients'
      fullPath: '/tenant/dashboards/clients'
      preLoaderRoute: typeof TenantDashboardsClientsRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/builder': {
      id: '/tenant/dashboards/builder'
      path: '/builder'
      fullPath: '/tenant/dashboards/builder'
      preLoaderRoute: typeof TenantDashboardsBuilderRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/dashboards/agents': {
      id: '/tenant/dashboards/agents'
      path: '/agents'
      fullPath: '/tenant/dashboards/agents'
      preLoaderRoute: typeof TenantDashboardsAgentsRouteImport
      parentRoute: typeof TenantDashboardsRoute
    }
    '/tenant/comms/templates': {
      id: '/tenant/comms/templates'
      path: '/tenant/comms/templates'
      fullPath: '/tenant/comms/templates'
      preLoaderRoute: typeof TenantCommsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/sms': {
      id: '/tenant/comms/sms'
      path: '/tenant/comms/sms'
      fullPath: '/tenant/comms/sms'
      preLoaderRoute: typeof TenantCommsSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/letters': {
      id: '/tenant/comms/letters'
      path: '/tenant/comms/letters'
      fullPath: '/tenant/comms/letters'
      preLoaderRoute: typeof TenantCommsLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/inbox': {
      id: '/tenant/comms/inbox'
      path: '/tenant/comms/inbox'
      fullPath: '/tenant/comms/inbox'
      preLoaderRoute: typeof TenantCommsInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/history': {
      id: '/tenant/comms/history'
      path: '/tenant/comms/history'
      fullPath: '/tenant/comms/history'
      preLoaderRoute: typeof TenantCommsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/email': {
      id: '/tenant/comms/email'
      path: '/tenant/comms/email'
      fullPath: '/tenant/comms/email'
      preLoaderRoute: typeof TenantCommsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/compliance': {
      id: '/tenant/comms/compliance'
      path: '/tenant/comms/compliance'
      fullPath: '/tenant/comms/compliance'
      preLoaderRoute: typeof TenantCommsComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/campaigns': {
      id: '/tenant/comms/campaigns'
      path: '/tenant/comms/campaigns'
      fullPath: '/tenant/comms/campaigns'
      preLoaderRoute: typeof TenantCommsCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/bulk': {
      id: '/tenant/comms/bulk'
      path: '/tenant/comms/bulk'
      fullPath: '/tenant/comms/bulk'
      preLoaderRoute: typeof TenantCommsBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/analytics': {
      id: '/tenant/comms/analytics'
      path: '/tenant/comms/analytics'
      fullPath: '/tenant/comms/analytics'
      preLoaderRoute: typeof TenantCommsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/crm/': {
      id: '/tenant/intake/crm/'
      path: '/tenant/intake/crm'
      fullPath: '/tenant/intake/crm/'
      preLoaderRoute: typeof TenantIntakeCrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/letters/': {
      id: '/tenant/comms/letters/'
      path: '/'
      fullPath: '/tenant/comms/letters/'
      preLoaderRoute: typeof TenantCommsLettersIndexRouteImport
      parentRoute: typeof TenantCommsLettersRoute
    }
    '/tenant/intake/crm/mappings': {
      id: '/tenant/intake/crm/mappings'
      path: '/tenant/intake/crm/mappings'
      fullPath: '/tenant/intake/crm/mappings'
      preLoaderRoute: typeof TenantIntakeCrmMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/crm/connect': {
      id: '/tenant/intake/crm/connect'
      path: '/tenant/intake/crm/connect'
      fullPath: '/tenant/intake/crm/connect'
      preLoaderRoute: typeof TenantIntakeCrmConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/intake/crm/activity': {
      id: '/tenant/intake/crm/activity'
      path: '/tenant/intake/crm/activity'
      fullPath: '/tenant/intake/crm/activity'
      preLoaderRoute: typeof TenantIntakeCrmActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/comms/letters/bulk': {
      id: '/tenant/comms/letters/bulk'
      path: '/bulk'
      fullPath: '/tenant/comms/letters/bulk'
      preLoaderRoute: typeof TenantCommsLettersBulkRouteImport
      parentRoute: typeof TenantCommsLettersRoute
    }
    '/tenant/comms/letters/builder': {
      id: '/tenant/comms/letters/builder'
      path: '/builder'
      fullPath: '/tenant/comms/letters/builder'
      preLoaderRoute: typeof TenantCommsLettersBuilderRouteImport
      parentRoute: typeof TenantCommsLettersRoute
    }
    '/tenant/comms/letters/approval': {
      id: '/tenant/comms/letters/approval'
      path: '/approval'
      fullPath: '/tenant/comms/letters/approval'
      preLoaderRoute: typeof TenantCommsLettersApprovalRouteImport
      parentRoute: typeof TenantCommsLettersRoute
    }
    '/tenant/debtors/$debtorId/notes/$noteId': {
      id: '/tenant/debtors/$debtorId/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/tenant/debtors/$debtorId/notes/$noteId'
      preLoaderRoute: typeof TenantDebtorsDebtorIdNotesNoteIdRouteImport
      parentRoute: typeof TenantDebtorsDebtorIdRoute
    }
    '/tenant/debtors/$debtorId/calls/$callId': {
      id: '/tenant/debtors/$debtorId/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/tenant/debtors/$debtorId/calls/$callId'
      preLoaderRoute: typeof TenantDebtorsDebtorIdCallsCallIdRouteImport
      parentRoute: typeof TenantDebtorsDebtorIdRoute
    }
  }
}

interface TenantDashboardsRouteChildren {
  TenantDashboardsAgentsRoute: typeof TenantDashboardsAgentsRoute
  TenantDashboardsBuilderRoute: typeof TenantDashboardsBuilderRoute
  TenantDashboardsClientsRoute: typeof TenantDashboardsClientsRoute
  TenantDashboardsComplianceRoute: typeof TenantDashboardsComplianceRoute
  TenantDashboardsCreditorsRoute: typeof TenantDashboardsCreditorsRoute
  TenantDashboardsExecutiveRoute: typeof TenantDashboardsExecutiveRoute
  TenantDashboardsExportsRoute: typeof TenantDashboardsExportsRoute
  TenantDashboardsFinanceRoute: typeof TenantDashboardsFinanceRoute
  TenantDashboardsScheduledRoute: typeof TenantDashboardsScheduledRoute
  TenantDashboardsSupervisorRoute: typeof TenantDashboardsSupervisorRoute
  TenantDashboardsIndexRoute: typeof TenantDashboardsIndexRoute
}

const TenantDashboardsRouteChildren: TenantDashboardsRouteChildren = {
  TenantDashboardsAgentsRoute: TenantDashboardsAgentsRoute,
  TenantDashboardsBuilderRoute: TenantDashboardsBuilderRoute,
  TenantDashboardsClientsRoute: TenantDashboardsClientsRoute,
  TenantDashboardsComplianceRoute: TenantDashboardsComplianceRoute,
  TenantDashboardsCreditorsRoute: TenantDashboardsCreditorsRoute,
  TenantDashboardsExecutiveRoute: TenantDashboardsExecutiveRoute,
  TenantDashboardsExportsRoute: TenantDashboardsExportsRoute,
  TenantDashboardsFinanceRoute: TenantDashboardsFinanceRoute,
  TenantDashboardsScheduledRoute: TenantDashboardsScheduledRoute,
  TenantDashboardsSupervisorRoute: TenantDashboardsSupervisorRoute,
  TenantDashboardsIndexRoute: TenantDashboardsIndexRoute,
}

const TenantDashboardsRouteWithChildren =
  TenantDashboardsRoute._addFileChildren(TenantDashboardsRouteChildren)

interface TenantPaymentsRouteChildren {
  TenantPaymentsPlansRoute: typeof TenantPaymentsPlansRoute
  TenantPaymentsSettlementsRoute: typeof TenantPaymentsSettlementsRoute
  TenantPaymentsIndexRoute: typeof TenantPaymentsIndexRoute
}

const TenantPaymentsRouteChildren: TenantPaymentsRouteChildren = {
  TenantPaymentsPlansRoute: TenantPaymentsPlansRoute,
  TenantPaymentsSettlementsRoute: TenantPaymentsSettlementsRoute,
  TenantPaymentsIndexRoute: TenantPaymentsIndexRoute,
}

const TenantPaymentsRouteWithChildren = TenantPaymentsRoute._addFileChildren(
  TenantPaymentsRouteChildren,
)

interface TenantSettingsRouteChildren {
  TenantSettingsDocumentAutomationRoute: typeof TenantSettingsDocumentAutomationRoute
  TenantSettingsStatusAutomationRoute: typeof TenantSettingsStatusAutomationRoute
  TenantSettingsStatusesRoute: typeof TenantSettingsStatusesRoute
  TenantSettingsIndexRoute: typeof TenantSettingsIndexRoute
}

const TenantSettingsRouteChildren: TenantSettingsRouteChildren = {
  TenantSettingsDocumentAutomationRoute: TenantSettingsDocumentAutomationRoute,
  TenantSettingsStatusAutomationRoute: TenantSettingsStatusAutomationRoute,
  TenantSettingsStatusesRoute: TenantSettingsStatusesRoute,
  TenantSettingsIndexRoute: TenantSettingsIndexRoute,
}

const TenantSettingsRouteWithChildren = TenantSettingsRoute._addFileChildren(
  TenantSettingsRouteChildren,
)

interface TenantCommsLettersRouteChildren {
  TenantCommsLettersApprovalRoute: typeof TenantCommsLettersApprovalRoute
  TenantCommsLettersBuilderRoute: typeof TenantCommsLettersBuilderRoute
  TenantCommsLettersBulkRoute: typeof TenantCommsLettersBulkRoute
  TenantCommsLettersIndexRoute: typeof TenantCommsLettersIndexRoute
}

const TenantCommsLettersRouteChildren: TenantCommsLettersRouteChildren = {
  TenantCommsLettersApprovalRoute: TenantCommsLettersApprovalRoute,
  TenantCommsLettersBuilderRoute: TenantCommsLettersBuilderRoute,
  TenantCommsLettersBulkRoute: TenantCommsLettersBulkRoute,
  TenantCommsLettersIndexRoute: TenantCommsLettersIndexRoute,
}

const TenantCommsLettersRouteWithChildren =
  TenantCommsLettersRoute._addFileChildren(TenantCommsLettersRouteChildren)

interface TenantDebtorsDebtorIdRouteChildren {
  TenantDebtorsDebtorIdCallsCallIdRoute: typeof TenantDebtorsDebtorIdCallsCallIdRoute
  TenantDebtorsDebtorIdNotesNoteIdRoute: typeof TenantDebtorsDebtorIdNotesNoteIdRoute
}

const TenantDebtorsDebtorIdRouteChildren: TenantDebtorsDebtorIdRouteChildren = {
  TenantDebtorsDebtorIdCallsCallIdRoute: TenantDebtorsDebtorIdCallsCallIdRoute,
  TenantDebtorsDebtorIdNotesNoteIdRoute: TenantDebtorsDebtorIdNotesNoteIdRoute,
}

const TenantDebtorsDebtorIdRouteWithChildren =
  TenantDebtorsDebtorIdRoute._addFileChildren(
    TenantDebtorsDebtorIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetpasswordRoute: ResetpasswordRoute,
  TenantinviteRoute: TenantinviteRoute,
  TenantAppointmentsRoute: TenantAppointmentsRoute,
  TenantAssignmentRoute: TenantAssignmentRoute,
  TenantAuditRoute: TenantAuditRoute,
  TenantBillingRoute: TenantBillingRoute,
  TenantDashboardsRoute: TenantDashboardsRouteWithChildren,
  TenantMovedFilesRoute: TenantMovedFilesRoute,
  TenantOnboardingRoute: TenantOnboardingRoute,
  TenantPaymentsRoute: TenantPaymentsRouteWithChildren,
  TenantRolesRoute: TenantRolesRoute,
  TenantSecurityRoute: TenantSecurityRoute,
  TenantSettingsRoute: TenantSettingsRouteWithChildren,
  TenantTeamDeckRoute: TenantTeamDeckRoute,
  TenantTeamsRoute: TenantTeamsRoute,
  TenantUsersRoute: TenantUsersRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantCommsAnalyticsRoute: TenantCommsAnalyticsRoute,
  TenantCommsBulkRoute: TenantCommsBulkRoute,
  TenantCommsCampaignsRoute: TenantCommsCampaignsRoute,
  TenantCommsComplianceRoute: TenantCommsComplianceRoute,
  TenantCommsEmailRoute: TenantCommsEmailRoute,
  TenantCommsHistoryRoute: TenantCommsHistoryRoute,
  TenantCommsInboxRoute: TenantCommsInboxRoute,
  TenantCommsLettersRoute: TenantCommsLettersRouteWithChildren,
  TenantCommsSmsRoute: TenantCommsSmsRoute,
  TenantCommsTemplatesRoute: TenantCommsTemplatesRoute,
  TenantDebtorsDebtorIdRoute: TenantDebtorsDebtorIdRouteWithChildren,
  TenantEngagementPhoneNumbersRoute: TenantEngagementPhoneNumbersRoute,
  TenantEngagementTemplateLibraryRoute: TenantEngagementTemplateLibraryRoute,
  TenantIntakeAuditRoute: TenantIntakeAuditRoute,
  TenantIntakeClientsRoute: TenantIntakeClientsRoute,
  TenantIntakeDedupeRoute: TenantIntakeDedupeRoute,
  TenantIntakeImportRoute: TenantIntakeImportRoute,
  TenantIntakeMassUpdateRoute: TenantIntakeMassUpdateRoute,
  TenantIntakeUploadRoute: TenantIntakeUploadRoute,
  TenantCaseFilesIndexRoute: TenantCaseFilesIndexRoute,
  TenantCommsIndexRoute: TenantCommsIndexRoute,
  TenantDebtorsIndexRoute: TenantDebtorsIndexRoute,
  TenantIntakeIndexRoute: TenantIntakeIndexRoute,
  TenantIntakeCrmActivityRoute: TenantIntakeCrmActivityRoute,
  TenantIntakeCrmConnectRoute: TenantIntakeCrmConnectRoute,
  TenantIntakeCrmMappingsRoute: TenantIntakeCrmMappingsRoute,
  TenantIntakeCrmIndexRoute: TenantIntakeCrmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
